### ISSUE TITLE
System.AggregateException 

### ISSUE THREAD

**Issue by BjornGrylls** [Zingabopp/SyncSaberService#12]
Got an error after it had downloaded all the songs. Seems to be the same as last version

Error:
[SyncSaberLib @ 21:43 - Info] Finished job 4421-MEGALOVANIA by jonahstone successfully.
[Program.cs_Main(165) @ 21:43 - Info] Exception downloading BeastSaberFeed: Bookmarks - System.AggregateException-One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SyncSaberLib.SyncSaber.DownloadSongs(Dictionary`2 queuedSongs, ValueTuple`2& skipped, Boolean useSongKeyAsOutputFolder)
   at SyncSaberLib.SyncSaber.DownloadSongsFromFeed(String feedType, IFeedSettings _settings)
   at SyncSaberConsole.Program.Main(String[] args) in C:\Users\Jared\source\repos\SyncSaberService\SyncSaberConsole\Program.cs:line 159

[SyncSaberLib @ 21:43 - Info] Finished downloading songs in 5 min 45 sec
Press any key to continue...

**Comment by Zingabopp** [comment]
This one might be a little trickier to find. AggregateExceptions are pretty vague and I'm probably not outputting the error correctly. I suspect there's a song you have bookmarked that isn't formatted properly in BeastSaber. Would you be able to look at your list of bookmarks and tell me what comes after Megalovania? I think the order should stay the same.

**Comment by BjornGrylls** [comment]
I get another error after this update. 

[SyncSaberLib @ 20:02 - Info] SyncSaberService 0.1.1
[SyncSaberLib @ 20:02 - Info] Using Beat Saber directory: D:\Programmer\GameLibraryOculus\Software\hyperbolic-magnetism-beat-saber
[SyncSaberLib @ 20:02 - Info] Scrapes loaded, 13929 BeatSaverSongs and 34804 ScoreSaber difficulties loaded
[SyncSaberLib @ 20:02 - Info] Playlist SyncSaber Playlist found in old playlist format.

[SyncSaberLib @ 20:02 - Info] Running the latest version of SyncSaberService.

[SyncSaberLib @ 20:02 - Info] Found 1 songs cached by SongCore.
[SyncSaberLib @ 20:02 - Info] Playlist BeatSaver Newest found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist BeastSaber Curator Recommended found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist BeastSaber Followings found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist BeastSaber Bookmarks found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist ScoreSaber Top Ranked found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist ScoreSaber Trending found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist ScoreSaber Top Played found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Playlist ScoreSaber Latest Ranked found in old playlist format.
[SyncSaberLib @ 20:02 - Info] Scraping new songs. Last Beat Saver scrape was at 18-06-2019 08:03:28. Last ScoreSaber scrape was at 18-06-2019 07:45:07.
[SyncSaberLib @ 20:02 - Info] 13971 songs available on 1397 pages
[SyncSaberLib @ 20:02 - Info] On page 0 / 1397
[SyncSaberLib @ 20:02 - Info] Scraped 50 new songs
[SyncSaberLib @ 20:02 - Info] On page 1
[SyncSaberLib @ 20:03 - Info] On page 2
[SyncSaberLib @ 20:03 - Info] Scraped 621 new songs


[SyncSaberLib @ 20:03 - Info] Downloading songs from bookmarks feed...
[SyncSaberLib @ 20:03 - Info] Finished checking pages, found 40 songs
[SyncSaberLib @ 20:03 - Info] Finished job d2-deltaMAX by roffle successfully.
[SyncSaberLib @ 20:03 - Info] Finished job 33-Bad Apple!! by dj505 successfully.
[SyncSaberLib @ 20:03 - Info] Finished job 18-Brain Power by roffle successfully.
[SyncSaberLib @ 20:03 - Info] Finished job 45-Give It Up by shedd successfully.
[SyncSaberLib @ 20:03 - Info] Finished job 3d-Sail (V2) by rellimjoe4 successfully.
[SyncSaberLib @ 20:03 - Info] Finished job 69-Dual of the Fates by tehsupertoilet successfully.
[DownloadBatch.cs_WorkDownloadQueue(30) @ 20:03 - Exception] Error while running job 4c-Everything will freeze by roffle
 - System.IO.IOException-The process cannot access the file 'C:\Users\bjorn\Downloads\SyncSaberService_x64\SyncSaberService\temp\temp-4c' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at SyncSaberLib.Utilities.EmptyDirectory(String directory, Boolean delete)
   at SyncSaberLib.Web.DownloadJob.<ExtractZipAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncSaberLib.Web.DownloadJob.<RunJobAsync>d__17.MoveNext()
[SyncSaberLib @ 20:03 - Info] Finished job 4c-Everything will freeze by roffle successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 92-Cantina Band by tehsupertoilet successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 5-Furioso Melodia by roffle successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 157-Seagulls! by paynter3d successfully.
[SyncSaberLib @ 20:04 - Info] Finished job d3-Bangarang by tmoss94 successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 29b-Lose My Mind (Radio Edit) by xolzec successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 3a4-Boulevard of Broken Dreams by downycat successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 3af-Us Against the World v1.3 by brainth successfully.
[SyncSaberLib @ 20:04 - Info] Finished job 25f-Reality Check Through The Skull by rickput successfully.
[SyncSaberLib @ 20:05 - Info] Finished job 15-Never Sleep Alone by shedd successfully.
[SyncSaberLib @ 20:05 - Info] Finished job 14-Thunder by maikyy successfully.
[SyncSaberLib @ 20:05 - Info] Finished job c5-Megalovania by sinlord successfully.
[SyncSaberLib @ 20:05 - Info] Finished job 5f5-Dark Sun by azone successfully.
[SyncSaberLib @ 20:05 - Info] Finished job 3a-TTFAF by freeek successfully.
[SyncSaberLib @ 20:05 - Info] Finished job 5d6-Bonfire by purphoros successfully.
[SyncSaberLib @ 20:06 - Info] Finished job 124-Rasputin (Funk Overload) by jobas successfully.
[SyncSaberLib @ 20:06 - Info] Finished job d5e-Can't Hold Us by ninjacat successfully.
[SyncSaberLib @ 20:06 - Info] Finished job 1f03-Monster by kolezan successfully.
[SyncSaberLib @ 20:06 - Info] Finished job d9c-Adventure Of A Lifetime by comrade successfully.
[SyncSaberLib @ 20:06 - Info] Finished job 1278-Turkish March (Ohm) by loloppe successfully.
[SyncSaberLib @ 20:06 - Info] Finished job 2f94-DeltaMAX by yun0 successfully.
[SyncSaberLib @ 20:07 - Info] Finished job 3f57-Switch by styngme successfully.
[SyncSaberLib @ 20:07 - Info] Finished job 1fef-Believer (100k ver.) by rustic successfully.
[SyncSaberLib @ 20:07 - Info] Finished job 4498-Re-Style - Get It Crackin by sarpestrazor successfully.
[SyncSaberLib @ 20:08 - Info] Finished job 4421-MEGALOVANIA by jonahstone successfully.
[SyncSaberLib @ 20:08 - Info] Finished job 44ff-MEGALOVANIA by ryger successfully.
[DownloadJob.cs_ExtractZipAsync(258) @ 20:08 - Exception] An exception occured while trying to move files into their final directory! - System.IO.IOException-The process cannot access the file 'C:\Users\bjorn\Downloads\SyncSaberService_x64\SyncSaberService\temp\temp-4a60' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at SyncSaberLib.Utilities.MoveFilesRecursively(DirectoryInfo source, DirectoryInfo target)
   at SyncSaberLib.Web.DownloadJob.<ExtractZipAsync>d__20.MoveNext()
[SyncSaberLib @ 20:08 - Error] Extraction failed for 4a60-Verbalase Megalovania Beatbox by chuckward
[SyncSaberLib @ 20:08 - Warning] Job failed, 4a60 failed during unzipping.
[SyncSaberLib @ 20:08 - Info] Finished job 48bc-Megalovania by pixelguymm successfully.
[SyncSaberLib @ 20:08 - Info] Finished job 48db-Party Don't Stop by raxanzeric successfully.
[SyncSaberLib @ 20:09 - Info] Finished job 4b3b-Highscore by sotarks successfully.
[SyncSaberLib @ 20:09 - Error] Failed to download 4a60 by chuckward
[SyncSaberLib @ 20:09 - Info] Downloaded 35 songs from BeastSaber's bookmarks feed in 5m 57s. Skipped 0 songs that already exist and 4 that are only in history, failed to download 1 songs..

[SyncSaberLib @ 20:09 - Info] Finished downloading songs in 6 min 22 sec
Press any key to continue...

**Comment by BjornGrylls** [comment]
I think I forgot to say the CustomSongs folder has disappered
But the "Everything will freeze" song is present in Beat Saber

**Comment by BjornGrylls** [comment]
Well I thought it had synced all the songs allthough the errors. But I'm missing 3-5 songs out of 2 pages.

**Comment by Zingabopp** [comment]
Thanks for the log. The CustomSongs folder isn't being used by Beat Saber anymore, the songs are now in "Beat Saber_Data\CustomLevels"

**Comment by BjornGrylls** [comment]
Just did a new sunc. It got the 2 new songs from bookmarks with no errors.

![image](https://user-images.githubusercontent.com/35100000/59979405-c82eb900-95e7-11e9-8674-b84e3c810144.png)
Custom levels look like this

**Comment by Zingabopp** [comment]
This should be fixed
