### ISSUE TITLE
Uncaught exception in Main() -

### ISSUE THREAD

**Issue by Bondyelwa** [Zingabopp/SyncSaberService#20]
Hello. I am getting this error when trying to run SyncSaberConsole.exe after I updated settings in SyncSaberService as well as bookmarked some songs on bsaber.com. Any idea why I might be getting this?

Uncaught exception in Main() - System.IO.DirectoryNotFoundException-Could not find a part of the path 'S:\Steam\steamapps\common\Beat Saber\UserData\SyncSaberHistory.txt'

Full error:
[SyncSaberLib @ 12:40 - Error] Beat Saber path  is invalid. Couldn't find 'Beat Saber.exe'
[SyncSaberLib @ 12:40 - Info] Found Steam installation of Beat Saber at S:\Steam\steamapps\common\Beat Saber
[SyncSaberLib @ 12:40 - Info] SyncSaberService 0.2.1
[SyncSaberLib @ 12:40 - Info] Using Beat Saber directory: S:\Steam\steamapps\common\Beat Saber
[SyncSaberLib @ 12:40 - Info] Scrapes loaded, 14810 BeatSaverSongs and 35916 ScoreSaber difficulties loaded
[SyncSaberLib @ 12:40 - Info] Found Beat Saber.exe
[SyncSaberLib @ 12:40 - Info] Updated Beat Saber directory path to S:\Steam\steamapps\common\Beat Saber
[SyncSaberLib @ 12:40 - Info] Playlist SyncSaber Playlist found in old playlist format.
[SyncSaberLib @ 12:40 - Info] Running the latest version of SyncSaberService.
[SyncSaberLib @ 12:40 - Info] Found 0 songs cached by SongCore.
[Program.cs_Main(291) @ 12:40 - Exception] Uncaught exception in Main() - System.IO.DirectoryNotFoundException-Could not find a part of the path 'S:\Steam\steamapps\common\Beat Saber\UserData\SyncSaberHistory.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SyncSaberLib.SyncSaber..ctor()
   at SyncSaberConsole.Program.Main(String[] args) in C:\Users\Jared\Source\Repos\Zingabopp\SyncSaberService\SyncSaberConsole\Program.cs:line 136

**Comment by Zingabopp** [comment]
Sorry for the late reply, I don't get notifications when new issues are created cause I'm still bad at GitHub. It looks like it's not creating the SyncSaberHistory.txt file for some reason. The only thing I can think of is you don't have a UserData folder in your Beat Saber folder (you don't have mods?). I'll fix this in a later version, for now just manually create a folder called UserData in your Beat Saber folder.

**Comment by Zingabopp** [comment]
Fixed in 0.2.2
