### ISSUE TITLE
This should not need a password

### ISSUE THREAD

**Issue by MagnumDopus** [Zingabopp/SyncSaberService#3]
The original sync saber did not need your password, just your username, this is a huge security risk.

**Comment by mazikowski** [comment]
I completely agree with @MagnumDopus. The in-game version simply scraped the publicly available bookmark pages. There is ZERO reason for this version to require any sort of login.

**Comment by Zingabopp** [comment]
The original SyncSaber hasn't actually gotten any songs from your Bookmarks or Followings feed for quite awhile (it doesn't error, it just thinks there weren't any songs there). BeastSaber changed at some point and made your Bookmarks and Followings private, so it does require a login. The only other option would be to have a way for people to log in through their web browser and copy the cookies it makes for the site, which probably isn't worth the trouble. For security concerns, make sure your password for BeastSaber isn't used anywhere else. Unless you're a mapper, I'm pretty sure there isn't anything critical in BeastSaber accounts.

**Comment by Zingabopp** [comment]
BeastSaber no longer requires a login cookie to get Bookmarks and Follows. Next version won't need a password.
